### ISSUE TITLE
conflict with wire laser pointer

### ISSUE THREAD

**Issue by Bryantdl7** [Patcher56/PatchProtect#83] opened 2014-11-14 00:49 UTC
see https://github.com/wiremod/wire/issues/704

my console is flooded with laserpointer/cl_init.lua:48: attempt to call method 'GetEyeTrace' (a nil value)

and the wireteam says its my prop protection; meaning you guys! xD

full error 

[ERROR] addons/wire/lua/weapons/laserpointer/cl_init.lua:48: attempt to call method 'GetEyeTrace' (a nil value)
  1. unknown - addons/wire/lua/weapons/laserpointer/cl_init.lua:48

**Comment by Domii894** [comment] 2015-01-04 01:04
So I tested it again (hard to believe but I really did!) and I still can't reproduce it.
I will close this issue now, but you can reopen it if you still think that this issue is created by PatchProtect. The error doesn't show exactly that the error should come from Patchprotect, so I think it is caused by another addon.

**Closed by Domii894** 2015-01-04 01:04 UTC
